### ISSUE TITLE
Getting secure boot enroll error.

### ISSUE THREAD

**Issue by iitzrohan** [sebastiaanfranken/systemd-boot-conversion#2]
![image](https://github.com/sebastiaanfranken/systemd-boot-conversion/assets/104166410/ee4fe704-938e-463d-865e-be892a65000f)

**Comment by iitzrohan** [comment]
i am using the secure boot with uki script. Also i am using a legion laptop with Ryzen 4800h and Nvidia Gtx 1650Ti
[Edit]
I used --microsoft option by editing the script. Now the system boots but my nvidia driver cant load because of secure boot. I enrolled the keys for it using mokutil. since that is no longer installed. How do i sign my nvidia driver now?

[Edit]
So, i installed mokutil and enrolled the keys which akmods generate. Now, after rebooting the enrollment window doesn't show up. So i cant add the key.

**Comment by sebastiaanfranken** [comment]
@iitzrohan Yes, key enrollment (into the shim) is not part of this script. This replaces the aforementioned shim entirely, so mokutil won't really do anything.

If you want/need that, revert the actions taken by the script and reinstall grub and it's toolchain for now. Sorry for not being a bigger help.

**Comment by iitzrohan** [comment]
@sebastiaanfranken Thanks for clearing that up. Is there any other way i can sign the nvidia modules? I really want to keep the systemd-boot with everything working.

**Comment by sebastiaanfranken** [comment]
@iitzrohan Maybe you can add the nvidia module(s) to the image (with `/et/dracut.conf.d/nvidia.conf`). Look at `man 5 dracut.conf`, the section on `add_drivers`. I've done something like that on my (non systemd-boot) main rig so I can see a nice GUI splash screen during kernel load. Not sure **if** that would work, though, but that's my first thought.

**Comment by sebastiaanfranken** [comment]
I am closing all current issues, since the repo has been "suspended" for now by me untill the change in Fedora 39 lands and all is stabilized. Once that happens and I have a stable landscape to work with I'll revive this repo and continue work.
