### ISSUE TITLE
Bricking

### ISSUE THREAD

**Issue by vari4bled** [sebastiaanfranken/systemd-boot-conversion#3]
Great work with the script. It does most of the work. I tried systemd-boot-install-fedora-no-secureboot.sh. It gave me an "invalid end of file" error, could not find where is the issue you might want to check. 
The bigger problem are the following lines: 
sed -i "^/initrd/d" "${LOADER_ENTRY}"
sed -i "^/linux/s/linux$/initrd/" "${LOADER_ENTRY}"
This will give sed unknown character issue during kernel-install and won't modify entries accordingly, so there will be a linux line pointing nowhere and bricking the loader.
I think you meant to do this instead:
sed -i "/^initrd/d" "${LOADER_ENTRY}"
sed -i "/^linux/s/linux$/initrd/" "${LOADER_ENTRY}"

**Comment by sebastiaanfranken** [comment]
Indeed, that's a typo. Thanks for reporting it @vari4bled . I fixed it in https://github.com/sebastiaanfranken/systemd-boot-conversion/commit/826682ad83f7966b30cab69118a8ba4a06710451
