### ISSUE TITLE
Linux 6.5 RC kernels won't load

### ISSUE THREAD

**Issue by sebastiaanfranken** [sebastiaanfranken/systemd-boot-conversion#4]
The current Linux 6.5 RC kernels (as shipped by Fedora) won't load properly. Loading them gives a error and the system halts booting.

This is known, but yet unknown *why* this is happening. That is being researched, and I am checking if this is something I can either work around or redo in the code.

If anyone has tips or hints, please share them in a comment!

**Comment by sebastiaanfranken** [comment]
Some research I've been doing seems to point to dracut being the culprit. If I configure a VM with the script from this repo but if I leave out the `uefi="yes"` setting in the `/etc/dracut.conf.d/systemd-boot.conf` file it \*seems\* to work.

**Comment by ruZeph** [comment]
Hello, now the proposal for clean systemd-boot is accepted in Fedora 39. Can you make a tutorial on how to do it when it releases?

(request btw)

**Comment by sebastiaanfranken** [comment]
> Hello, now the proposal for clean systemd-boot is accepted in Fedora 39. Can you make a tutorial on how to do it when it releases?
> 
> (request btw)

That's a different issue in that case. If the change is accepted, chances are very high there will be a page on the Fedora wiki about this, which is where I'll be directing everyone. Though that kind of change is not something the Fedora team will support with a "running" install I suspect, so a reinstall (with the option `rd.sdboot`) will be required.

**Comment by sebastiaanfranken** [comment]
I am closing all current issues, since the repo has been "suspended" for now by me untill the change in Fedora 39 lands and all is stabilized. Once that happens and I have a stable landscape to work with I'll revive this repo and continue work.
